### ISSUE TITLE
Can't convert FSKL to Armature

### ISSUE THREAD

**Issue by EnderTheHunter** [Houmgaor/MHFrontier-Blender-Addon#3]
Hello,
I tried with a friend to import Frontier models with your tool in Blender 2.91. Sadly, we can't find the "Convert FSKL to Armature" button you're talking about in the README.
Is there something we're missing ?

![image](https://github.com/user-attachments/assets/5b3aa9a5-8b2b-40eb-96fb-21efd2b03c1b)

**Comment by Houmgaor** [comment]
Fixed, the option needed to be added to a menu, probably broken by a Blender update.
